const card1 = document.getElementById('card-1');
const div1left = document.createElement('div');
div1left.setAttribute('id', 'div-1--left');
const img = document.createElement('img');
img.setAttribute('id', 'card-1-img');
img.setAttribute('src', 'images/recenttitle.svg');
img.setAttribute('alt', 'Gymfit logo');
div1left.append(img);
card1.append(div1left);
const div1right = document.createElement('div');
div1right.setAttribute('id', 'div-1--right');
const h2 = document.createElement('h2');
h2.setAttribute('class', 'works-title-text');
h2.setAttribute('id', 'works-title-text');
h2.innerHTML = 'Multi-Post Stories';
div1right.append(h2);
const p = document.createElement('p');
p.innerHTML = "A daily selection of privately personalized reads no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.";
p.setAttribute('id', 'card-1-text');
div1right.append(p);
const skilltext = document.createElement('div');
skilltext.setAttribute('id', 'skill-text');
div1right.append(skilltext);
const ul = document.createElement('ul');
const li1 = document.createElement('li');
li1.setAttribute('class', 'read-text');
li1.innerHTML = 'css';
ul.append(li1);
const li2 = document.createElement('li');
li2.setAttribute('class', 'read-text');
li2.innerHTML = 'html';
ul.append(li2);
const li3 = document.createElement('li');
li3.setAttribute('class', 'read-text');
li3.innerHTML = 'bootstrap';
ul.append(li3);
const li4 = document.createElement('li');
li4.setAttribute('class', 'read-text');
li4.innerHTML = 'Ruby';
ul.append(li4);
skilltext.append(ul);
div1right.append(skilltext);
const button = document.createElement('button');
button.setAttribute('class', 'div-1--right-btn');
button.innerHTML = 'See Project';
div1right.append(button);
card1.append(div1right);